name: CI Pipeline

on:
  push:
    branches: [ develop, master, feature/add-docker-build ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies (API)
        run: |
          cd api
          npm install

      - name: Run Tests (API)
        run: |
          cd api
          npm test

      - name: Install Dependencies (Worker)
        run: |
          cd worker
          npm install

      - name: Run Tests (Worker)
        run: |
          cd worker
          npm test

      - name: Build Docker Image (API)
        run: |
          docker build -t devops-api ./api

      - name: Build Docker Image (Worker)
        run: |
          docker build -t devops-worker ./worker
